name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./HotelAvailabilityApi/HotelAvailabilityApi.csproj
      - name: Build
        run: dotnet build ./HotelAvailabilityApi/HotelAvailabilityApi.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./HotelAvailabilityApi/HotelAvailabilityApi.csproj --no-build --verbosity normal
        continue-on-error: true
      - name: Publish
        run: dotnet publish ./HotelAvailabilityApi/HotelAvailabilityApi.csproj --configuration Release --output ./publish --no-build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
